### ISSUE TITLE
Request: Support for null shop in menus.yml

### ISSUE THREAD

**Issue by SLASHLogin** [SirLeezus/OneStopShop#12]
We're using one of the menus as placeholder. It does not lead to any of the shops and we had it set shop as nothing. Unfortunately 1.1.3 breaks this, and disables the plugin after seeing null. Would there be an option to accept nulls instead of crashing the plugin?
```
[17:11:28 INFO]: [OneStopShop] Enabling OneStopShop v1.1.3
[17:11:28 ERROR]: Error occurred while enabling OneStopShop v1.1.3 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at lee.code.onestopshop.menusystem.DataMenuUtility.setShop(DataMenuUtility.java:43) ~[?:?]
        at lee.code.onestopshop.Data.lambda$null$0(Data.java:219) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at lee.code.onestopshop.Data.lambda$loadMenus$1(Data.java:190) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at lee.code.onestopshop.Data.loadMenus(Data.java:173) ~[?:?]
        at lee.code.onestopshop.Data.loadData(Data.java:153) ~[?:?]
        at lee.code.onestopshop.OneStopShop.onEnable(OneStopShop.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-682]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Paper-682]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-682]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-682]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-682]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-682]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-682]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-682]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-682]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[17:11:28 INFO]: [OneStopShop] Disabling OneStopShop v1.1.3
```

```
"8":
        name: "&c&lRanks &7(/ranks)"

        material: NETHER_STAR

        menu-slot: 22

        shop: null
```

**Comment by LeeTheTech** [comment]
I can resolve this soon!

**Comment by LeeTheTech** [comment]
Fixed in the last version!
