### ISSUE TITLE
Error entering weapons category.

### ISSUE THREAD

**Issue by Lester-R** [SirLeezus/OneStopShop#17]
i've added spell tipped arrows. then this happens.

`[2021-07-19 21:19:54]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.ConfigurationSection.getConfigurationSection(String)" is null
[2021-07-19 21:19:54]: at lee.code.onestopshop.xseries.XItemStack.deserialize(XItemStack.java:536) ~[?:?]
[2021-07-19 21:19:54]: at lee.code.onestopshop.Data.lambda$loadShops$2(Data.java:271) ~[?:?]
[2021-07-19 21:19:54]: at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
[2021-07-19 21:19:54]: at lee.code.onestopshop.Data.loadShops(Data.java:252) ~[?:?]
[2021-07-19 21:19:54]: at lee.code.onestopshop.Data.loadData(Data.java:154) ~[?:?]
[2021-07-19 21:19:54]: at lee.code.onestopshop.OneStopShop.onEnable(OneStopShop.java:49) ~[?:?]
[2021-07-19 21:19:54]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-R0.1-38e6c03da15-ca0fe5b5514-5f772da93d3.jar:3180-Spigot-38e6c03-ca0fe5b]
[2021-07-19 21:19:54]: at java.lang.Thread.run(Thread.java:831) [?:?]`

I think that's all of the error.

**Comment by Lester-R** [comment]
Some of the stuff it does anyway, some categories i can't open. And i can't sell.

**Comment by LeeTheTech** [comment]
Could you link your configs, and what do you mean by a "spell" tipped arrow? Also, what spigot version are you using?

**Comment by SirLeezus** [comment]
Also, what spigot version are you using?

**Comment by Lester-R** [comment]
Spigot
Build: R0.1-d03d7f12a44-c851639c505-eec4aab0016 (1.17.1) 

...I don't think i can link them, i'm on nodecraft. I think it's a missed line or syntax error.
...So i spent most of the night just GUIing everything in and it's... sort of fine now.

**Comment by Lester-R** [comment]
[https://github.com/Lester-R/configs](url)

Will that do?
